package com.rite.pillcounting.core.room.models

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.PrimaryKey

/**
 * Room entity for one 128-d SFace embedding captured during registration.
 *
 * Description:
 * Each [FaceProfileEntity] has exactly 3 rows here — one per capture angle
 * (front / tilt-left / tilt-right) — mirroring `standalone_face_tf.py`'s
 * 3-embeddings-per-user gallery design, but directed capture instead of
 * passive frame accumulation.
 *
 * What it does:
 * - Stores the raw 128 float32 values as a [ByteArray] blob.
 * - `ON DELETE CASCADE` removes embeddings automatically when their profile
 *   is deleted.
 *
 * @param id Room primary key, autogenerated.
 * @param faceProfileId Foreign key to [FaceProfileEntity.id].
 * @param angle One of "FRONT", "TILT_LEFT", "TILT_RIGHT" — see `FaceCaptureAngle`.
 * @param vec 128 float32s, little-endian, as produced by [java.nio.ByteBuffer].
 *
 * Example Usage:
 * val embedding = FaceEmbeddingEntity(faceProfileId = 1L, angle = "FRONT", vec = byteArrayOf())
 */
@Entity(
    tableName = "face_embeddings",
    foreignKeys = [
        ForeignKey(
            entity = FaceProfileEntity::class,
            parentColumns = ["id"],
            childColumns = ["faceProfileId"],
            onDelete = ForeignKey.CASCADE
        )
    ]
)
data class FaceEmbeddingEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0L,
    val faceProfileId: Long,
    val angle: String,
    val vec: ByteArray
)
