package com.rite.pillcounting.core.room.models

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Room entity representing one enrolled "Quick Access" face profile.
 *
 * Description:
 * A local-only record created when an operator registers their face via the
 * Settings > Face Recognition flow. Distinct from [UserEntity] (the backend
 * account record) — [email] here is a snapshot copied from the logged-in
 * session at registration time, not an ongoing link to that account.
 *
 * What it does:
 * - Holds the display identity (first/last name) shown in the Quick Access
 *   Users list.
 * - [isEnabled] backs the list screen's per-row toggle.
 * - [lastUsedAt] is updated on every successful verify match.
 *
 * @param id Room primary key, autogenerated.
 * @param firstName Typed at registration.
 * @param lastName Typed at registration.
 * @param email Copied from the session's account email at registration time; nullable if unavailable.
 * @param isEnabled Whether this profile currently participates in verify matching.
 * @param createdAt Epoch millis when the profile was created.
 * @param lastUsedAt Epoch millis of the last successful verify match, or null if never matched.
 * @param faceImagePath Absolute path to the saved FRONT-angle face JPEG in internal storage, or null if not captured.
 *
 * Example Usage:
 * val profile = FaceProfileEntity(firstName = "Bruce", lastName = "Wayne", email = null, createdAt = System.currentTimeMillis())
 */
@Entity(tableName = "face_profiles")
data class FaceProfileEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0L,
    val firstName: String,
    val lastName: String,
    val email: String?,
    val isEnabled: Boolean = true,
    val createdAt: Long,
    val lastUsedAt: Long? = null,
    val faceImagePath: String? = null
)
